name: release

on:
    push: ~

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: cli/gh-extension-precompile@v2.2.0
